_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

# code ajouté pour l'administration du site des gibbons
_gibbons_admin:
  resource: "@GibbonsMasquesCoreBundle/Resources/config/routing_dev.yml"
  prefix: /_super_gibbons
# fin du code ajouté

_main:
    resource: routing.yml
